#define MAX_RESERVATION_SIZE 256
#define STATE_ACCESS_DELAY_US 500000  // 500ms
#define MAX_JOB_FILE_NAME_SIZE 256
#define FIFO_NAME_SIZE 40
#define MAX_SESSION_COUNT 8
#define OP_SETUP '1'
#define OP_QUIT '2'